name: Hardhat Test Suite

on:
  pull_request:
  workflow_call:
    secrets:
      MAINNET_RPC_URL:
        required: true

jobs:
  hardhat:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [executooor-ethers]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn --immutable

      - uses: actions/cache@v4
        with:
          path: |
            packages/${{ matrix.package }}/cache/
            packages/${{ matrix.package }}/artifacts/
          key: ${{ github.base_ref || github.ref_name }}-${{ matrix.package }}-hardhat

      - run: yarn workspace ${{ matrix.package }} test
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
